// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhG925nsYNXjEIrcKMRY1TtJnQkt4a_Qk',
    appId: '1:53083713040:web:2216120cd96351b167a495',
    messagingSenderId: '53083713040',
    projectId: 'moova-af072',
    authDomain: 'moova-af072.firebaseapp.com',
    databaseURL: 'https://moova-af072-default-rtdb.firebaseio.com',
    storageBucket: 'moova-af072.firebasestorage.app',
    measurementId: 'G-HRHECL4YR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-cF7inqgMZIyOxKoqS_oLa0PmkmGEP-Y',
    appId: '1:53083713040:android:c49088320759e65567a495',
    messagingSenderId: '53083713040',
    projectId: 'moova-af072',
    databaseURL: 'https://moova-af072-default-rtdb.firebaseio.com',
    storageBucket: 'moova-af072.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiBq2pvPdFA9_S6rZcSwBLR_G4NHZL65U',
    appId: '1:53083713040:ios:754428a2364ae1c467a495',
    messagingSenderId: '53083713040',
    projectId: 'moova-af072',
    databaseURL: 'https://moova-af072-default-rtdb.firebaseio.com',
    storageBucket: 'moova-af072.firebasestorage.app',
    iosBundleId: 'com.example.emisor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiBq2pvPdFA9_S6rZcSwBLR_G4NHZL65U',
    appId: '1:53083713040:ios:754428a2364ae1c467a495',
    messagingSenderId: '53083713040',
    projectId: 'moova-af072',
    databaseURL: 'https://moova-af072-default-rtdb.firebaseio.com',
    storageBucket: 'moova-af072.firebasestorage.app',
    iosBundleId: 'com.example.emisor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhG925nsYNXjEIrcKMRY1TtJnQkt4a_Qk',
    appId: '1:53083713040:web:24ef5e62c727f40a67a495',
    messagingSenderId: '53083713040',
    projectId: 'moova-af072',
    authDomain: 'moova-af072.firebaseapp.com',
    databaseURL: 'https://moova-af072-default-rtdb.firebaseio.com',
    storageBucket: 'moova-af072.firebasestorage.app',
    measurementId: 'G-QF7T0JVPE9',
  );
}
